### ISSUE TITLE
Building fails on Arch Linux

### ISSUE THREAD

**Issue by agent28** [AliceStats/Alice#8]
Building fails with the following error:

```
[ 96%] Building CXX object CMakeFiles/alice-verify.dir/example/verify.cpp.o
Linking CXX executable alice-verify
/usr/bin/ld: CMakeFiles/alice-verify.dir/example/verify.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Adding -lpthread flag for the GCC compiler in CMakeLists.txt apparently solved the issue for me as I was able to build successfully.

**Comment by invokr** [comment]
Hi,
thanks for reporting this, it's definitely a bug. I will look into linking pthread to alice-validate and conditionally adding it to the examples on linux only. 

Robin
