### ISSUE TITLE
New Replay Version

### ISSUE THREAD

**Issue by KenBeanNet** [AliceStats/Alice#9]
Hey,

Ever since the new replay version released maybe about 7 days ago, I can't get CombatLogs to work. 

Everything else seems to work fine (UMs and such).  The header ID is always 0.  Not sure?

**Comment by invokr** [comment]
I don't have a test case for the combat logs right now. If you post a minimal code example I'll look into it.

**Comment by KenBeanNet** [comment]
Thanks for quick response.

[code] 
handlerRegisterCallback(handler, msgNet, svc_GameEvent, cpj, handleEvent);

cpj_event_result_t cpj::handleCombatLog(const CSVCMsg_GameEvent *e) {
    int type = e->keys(0).val_byte();
    switch (type) {
    default: {
        //printf("Unhandled handleCombatLog by Type %d.\n", type);
        return CPJ_EVENT_REASON_NACK;
    }
}
[/code]

Worked fine from your examples, but as of about 5-7 days ago, it broke.  The type is always 0.  The keys is always set to size 9.

**Comment by KenBeanNet** [comment]
Sorry, I cant include all my code, would be way to long.  But its pretty basic.  Pretty sure what ever changed, broke something.  Are you in IRC?
